#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
set -euo pipefail
#set -x
#set -x 将在命令执行前打印出命令 方便调试



acme.sh  --issue --dns dns_dp  -d  aihlp.com  -d *.aihlp.com
cd /home/li/.acme.sh/aihlp.com
openssl pkcs12 -export -inkey aihlp.com.key -in aihlp.com.cer -out aihlp.com.pfx -password pass:zek65c43uns



