<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.4.1 setup script
 * Date: Thu, 11 Jul 2013 08:30:59 +0800
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['tracking_version_auto_create'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = 'a8435retb7cret56454.,/346d';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['UserprefsDeveloperTab'] = true;
$cfg['Error_Handler']['display'] = true;
$cfg['Error_Handler']['gather'] = true;
$cfg['DBG']['sql'] = false;
$cfg['PersistentConnections'] = true;
$cfg['QueryHistoryDB'] = true;
$cfg['RetainQueryBox'] = true;
$cfg['ShowDbStructureCreation'] = true;
$cfg['ShowDbStructureLastUpdate'] = true;
$cfg['ShowDbStructureLastCheck'] = true;
$cfg['HideStructureActions'] = false;
$cfg['ShowAll'] = true;
$cfg['ShowDisplayDirection'] = true;
$cfg['Export']['sql_dates'] = true;
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
?>