#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
set -euo pipefail
#set -x
#set -x 将在命令执行前打印出命令 方便调试

function gc()
{
        var=$1  
        echo  git gc --auto   $file 
        git gc --auto
        echo 
}
function funall(){

    for file in $work_path/*
    do  
    if test -d $file
    then    
        
        if [   -d ${file}'/.git'   ] ; then 
          
        cd $file               
        gc 
        fi 
    fi
   done
        
}
cur=$(dirname $(dirname $(readlink -f $0)))
work_path=$cur
funall $*
work_path=$cur/AndroidLib
funall $*
work_path=$cur/yt
funall $*

