#! /bin/bash
#push all

function pullall(){

    for file in $work_path/*
    do  
    if test -d $file
    then    
        
        if [   -d ${file}'/.git'   ] ; then 
          
        cd $file       
         
        mm=$(git remote) ;
		
	    for var in $mm ; do

        if [[ $# -gt 0 ]]; then
            rt=$(echo $* | grep -w $var)
 #           echo ALL:$*  var:$var  rt  :  $rt
            if [[ "$rt"xx = xx ]]; then            
                continue ;
            else                 
                echo Git remote remove $var  from  $file     
                git remote remove $var
            fi            
        fi 
        done 		
        fi   
    fi
    done    
}
cur=$(dirname $(dirname $(readlink -f $0)))
work_path=$cur
pullall $*
work_path=$cur/AndroidLib
pullall $*
work_path=$cur/yt
pullall $*






