#! /bin/bash
#set -e
if [ ! -n "$1" ] ;
then   
echo "请传入远程主机" ;
exit
fi
host=$1
echo /etc/firewalld/services/ 
rsync -ahAX   /etc/firewalld/services/ 	$host:/etc/firewalld/services/
echo  $host  firewall-cmd --reload
ssh $host 'firewall-cmd --reload'




















