#! /bin/bash
#set -e
if [ ! -n "$1" ] ;
then   
echo "请传入远程主机" ;
exit
fi
host=$1
echo /etc/pacman.d/ 
sudo rsync -ahAX /etc/pacman.d/   $host:/etc/pacman.d/

echo /etc/sudoers 
sudo rsync -ahAX /etc/sudoers  $host:/etc/
  
echo /etc/conf.d/reflector.conf 
rsync -ahAX   /etc/conf.d/reflector.conf 							$host:/etc/conf.d/
  
echo  /etc/locale.conf 
rsync -ahAX  /etc/locale.conf 										$host:/etc/
  
echo /etc/security/limits.conf   	
rsync -ahAX /etc/security/limits.conf   								$host:/etc/security/
  
echo /etc/environment 
rsync -ahAX /etc/environment 											$host:/etc/
  
echo /etc/profile
rsync -ahAX /etc/profile   $host:/etc/
  
echo /etc/pacman.conf
rsync -ahAX /etc/pacman.conf  $host:/etc/
  
echo  /etc/pacman.d/archlinuxcn-mirrorlist
rsync -ahAX  /etc/pacman.d/archlinuxcn-mirrorlist  $host:/etc/pacman.d/
  
echo /etc/skel/.config/locale.conf
rsync -ahAX /etc/skel/.config/locale.conf   $host:/etc/skel/.config/
  
echo /etc/xdg/reflector/
rsync -ahAX /etc/xdg/reflector/  $host:/etc/xdg/reflector/

echo /etc/sysctl.d
rsync -ahAX --delete /etc/sysctl.d/  $host:/etc/sysctl.d/

   
   
echo  firewalld
rsync-firewalld $host

