#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
set -euo pipefail
#set -x
#set -x 将在命令执行前打印出命令 方便调试



cd ~/.config/google-chrome
git add --all 
git commit -m Auto
push


cd ~/.mozilla
git add --all 
git commit -m Auto
push

cd ~/.config/JetBrains
git add --all 
git commit -m Auto
push


cd ~/

git add --all 
git commit -m Auto
push


