#! /bin/bash
cd ~/.config/google-chrome
git add --all 
git commit -m Auto
push


cd ~/.mozilla
git add --all 
git commit -m Auto
push

cd ~/.config/JetBrains
git add --all 
git commit -m Auto
push


cd ~/

git add --all 
git commit -m Auto
push


